[server]
hostname = "${MAIL_DOMAIN}"

[server.tls]
enabled = true
implicit = false

[server.tls.certificate]
cert = "/opt/stalwart-mail/certs/fullchain.pem"
key = "/opt/stalwart-mail/certs/privkey.pem"

# Другие настройки сервера
[storage]
data-dir = "/opt/stalwart-mail/data"

[queue]
directory = "/opt/stalwart-mail/queue"

[logging]
directory = "/opt/stalwart-mail/logs"
