[server]
hostname = "${MAIL_DOMAIN}"

[server.listener."smtp"]
bind = ["0.0.0.0:25"]
protocol = "smtp"

[server.listener."submission"]
auth = true
bind = ["0.0.0.0:587"]
protocol = "smtp"

[server.listener."submissions"]
auth = true
bind = ["0.0.0.0:465"]
protocol = "smtp"
tls.implicit = true

[server.listener."imap"]
bind = ["0.0.0.0:143"]
protocol = "imap"

[server.listener."imaps"]
bind = ["0.0.0.0:993"]
protocol = "imap"
tls.implicit = true

[server.listener."http"]
bind = ["0.0.0.0:8080"]
protocol = "http"

[certificate."default"]
cert = "/opt/stalwart-mail/certs/fullchain.pem"
default = true
private-key = "/opt/stalwart-mail/certs/privkey.pem"

[storage]
blob = "postgresql"
data = "postgresql"
directory = "internal"
fts = "postgresql"
lookup = "postgresql"

[store."postgresql"]
port = ${DB_PORT}
database = "${DB_NAME}"
host = "${DB_HOST}"
password = "${DB_PASSWORD}"
timeout = "15s"
type = "postgresql"
user = "${DB_USER}"

[store."postgresql".pool]
max-connections = 10

[directory."internal"]
admin-email = "${ADMIN_EMAIL}"
store = "postgresql"
type = "internal"

[authentication.fallback-admin]
secret = "${ADMIN_PASSWORD}"
user = "admin"
