[server]
hostname = "${MAIL_DOMAIN}"

[storage]
data = "/opt/stalwart-mail/data"

[storage.blob]
path = "/opt/stalwart-mail/data/blob"
type = "fs"

[storage.lookup]
path = "/opt/stalwart-mail/data/lookup"
type = "fs"

[storage.directory]
path = "/opt/stalwart-mail/data/directory"
type = "fs"

[storage.session]
path = "/opt/stalwart-mail/data/session"
type = "fs"

[storage.oauth2]
path = "/opt/stalwart-mail/data/oauth2"
type = "fs"

[storage.fts]
path = "/opt/stalwart-mail/data/fts"
type = "fs"

[storage.jmap]
path = "/opt/stalwart-mail/data/jmap"
type = "fs"

[storage.queue]
path = "/opt/stalwart-mail/queue"
type = "fs"

[certificate]
cert = "/opt/stalwart-mail/certs/fullchain.pem"
private-key = "/opt/stalwart-mail/certs/privkey.pem"

[directory]
type = "internal"

[directory.internal]
admin-email = "${ADMIN_EMAIL}"

[smtp]
enabled = true

[smtp.server]
bind = ["0.0.0.0:25", "0.0.0.0:587"]
enabled = true

[smtp.submission]
auth = true
bind = ["0.0.0.0:465"]
enabled = true
tls.implicit = true

[imap]
enabled = true

[imap.server]
bind = ["0.0.0.0:143"]
enabled = true

[imap.server.tls]
bind = ["0.0.0.0:993"]
enabled = true
implicit = true

[jmap]
enabled = true

[jmap.server]
bind = ["0.0.0.0:8080"]
enabled = true

[webadmin]
bind = ["0.0.0.0:8080"]
enabled = true
