version: "3.8"
services:
  mail:
    build: .
    container_name: stalwart-mail
    env_file:
      - .env
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    ports:
      - "25:25" # SMTP
      - "587:587" # SMTP с TLS
      - "465:465" # SMTP SSL
      - "143:143" # IMAP
      - "993:993" # IMAP SSL
      - "8080:8080" # Веб-интерфейс
    volumes:
      - mail-config:/opt/stalwart-mail/etc
      - mail-data:/opt/stalwart-mail/data
      - mail-certs:/opt/stalwart-mail/certs
      - mail-queue:/opt/stalwart-mail/queue
      - mail-logs:/opt/stalwart-mail/logs
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    entrypoint: ["/opt/stalwart-mail/scripts/docker-entrypoint.sh"]
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  mail-config:
  mail-data:
  mail-certs:
  mail-queue:
  mail-logs:
  letsencrypt:
