version: "3.8"

services:
  mail:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    ports:
      - "25:25" # SMTP
      - "587:587" # SMTP c TLS
      - "465:465" # SMTP SSL
      - "143:143" # IMAP
      - "993:993" # IMAP SSL
      - "8081:8080" # Веб-интерфейс
    volumes:
      - ./mail_data:/opt/stalwart-mail
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
