version: "3.8"
services:
  mail:
    image: stalwartlabs/mail-server:latest
    container_name: stalwart-mail
    environment:
      - SMTP_SERVER_HOSTNAME=mail.equiply.ru
      - ADMIN_PASSWORD=your_admin_password
    ports:
      - "25:25" # SMTP
      - "587:587" # SMTP с TLS
      - "465:465" # SMTP SSL
      - "143:143" # IMAP
      - "993:993" # IMAP SSL
      - "8080:8080" # Веб-интерфейс
    volumes:
      - mail-data:/opt/stalwart-mail
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  mail-data:
